# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# Uncomment this line if you're using Swift
# use_frameworks!

#pod 'DeskKit', '~> 2.1.0'
pod 'DeskAPIClient', :git => 'https://github.com/forcedotcom/DeskApiClient-ObjC.git', :branch => 'develop'
pod 'DeskKit', :git => 'git@github.com:forcedotcom/DeskMobileSDK-iOS.git', :branch => 'tickets/MSDKI-39-Make-it-easier-for-clients-to-style-the-SDK-differently-than-their-app'
