# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# Uncomment this line if you're using Swift
# use_frameworks!

target 'DeskKitExample' do
    pod 'DeskKit', '~> 4.0'
end
